import WishlistCounter from "@/components/WishlistCounter";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <header className="md:container md:mx-auto">
        <nav
          className="flex items-center gap-2 hover:underline hover:underline-offset-4"
        >
          <ul className="flex justify-between	">
            <li>
              <a href="/">Logo Icon</a>
            </li>
            <li>
              <a href="/wishlist">
                <WishlistCounter />
              </a>
            </li>
          </ul>
        </nav>
      </header>

      {children}
    </body>
  </html>
);


export default RootLayout;